<?php
/**
 * Implementation of hook_menu().
 */
function airnewzealand_menu()
{   
  // $items['admin/config/airnewzealand'] = array(
  //   'title' => '新西兰航空',
  //   'description' => '新西兰航空微信页面设置',
  //   'position' => 'right',
  //   'weight' => -5,
  //   'page callback' => 'system_admin_menu_block_page',
  //   'access arguments' => array('administer site configuration'),
  //   'file' => 'system.admin.inc',
  //   'file path' => drupal_get_path('module', 'system')
  //   );
  //
    $items['admin/config/services/airnezealand-settings']= array(
    'title' =>        '设置',
    'description'=>   '设置相关微信服务参数',	
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oather_form'),
    'access arguments' => array('administer site configuration'),
    'type'=>          MENU_NORMAL_ITEM
    );
    $items['wechat/author'] = array(
    'page callback' => 'get_user_info',
    'access arguments' => array('access content'),
    'type'=> MENU_CALLBACK
    );
    $items['wechat/infouload'] = array (
    'page callback' => 'upload_user_info',
    'access arguments' => array('access content'),
    'type'=> MENU_CALLBACK
    );
    $items['wechat/getticket'] = array (
    'page callback' => 'get_ticket',
    'access arguments' => array('access content'),
    'type'=> MENU_CALLBACK
    );
    $items['wechat/sharecount'] = array(
    'page callback' => 'get_share_count',
    'access arguments' => array('access content'),
    'type'=> MENU_CALLBACK
    );

    return $items;
}
/**
 * Implements hook_help().
 */
function airnewzealand_help($path,$arg)
{
    $output='';
    switch ($path) {
    	case 'admin/help/airnewzealand':
    		$output= '新西兰航空微信活动服务';
    		break;
    }
    return $output;
}

function oather_form()
{   
  drupal_set_message('load success');
  $form['appid']=array(
	'#title' =>'微信服务appID',
	'#type'  =>'textfield',
	'#required' =>TRUE,
	'#default_value'=>variable_get('wechatappid', '')
	);
  $form['appsecret']=array(
	'#title' =>'微信服务appSECRET',
	'#type'  =>'textfield',
	'#required' =>TRUE,
	'#default_value'=>variable_get('wechatappsecret', '')
	);
	$form['submit'] = array(
	'#value' => '提交',
	'#type' => 'submit',
	'#required' => TRUE,
	'#submit' =>array('oather_form_submit'),
	'#validate' => array('oather_form_validate')
	);
	return $form;

}
function oather_form_submit(&$form,&$form_state)
{
	variable_set('wechatappid', $form_state['values']['appid']);
	variable_set('wechatappsecret',$form_state['values']['appsecret']);
	//drupal_set_message('信息存入成功');
    //drupal_set_message(variable_get('wechatappid', ''));
    //drupal_set_message(variable_get('wechatappsecret', ''));

}

function oather_form_validate($form,$form_state)
{
    if(drupal_strlen($form_state['values']['appid'])<5)
    {
    	form_set_error('APPid长度不合法');
    }
    if(drupal_strlen($form_state['values']['appsecret'])<10)
    {
    	form_set_error('APPsecret长度不合法');
    }
}
function get_user_info()
{  
    $user_agent=$_SERVER['HTTP_USER_AGENT'];
    if (strpos($user_agent, 'MicroMessenger') === false) {
    // 非微信浏览器禁止浏览
    //header("location: http://www.baidu.com");
    drupal_goto('html/pc.html');
    drupal_exit();
    } 
    if (!isset($_GET['code'])){
      //触发微信返回code码
        $baseUrl = urlencode('http://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']);
        $url = __CreateOauthUrlForCode($baseUrl);
        Header("Location: $url");
        exit();
      }
    $code=$_GET['code'];
    $appId=variable_get('wechatappid', '');
    $appSecret=variable_get('wechatappsecret', '');
    $token_url="https://api.weixin.qq.com/sns/oauth2/access_token?appid=$appId&secret=$appSecret&code=$code&grant_type=authorization_code";
    $backjson=json_decode(http_get($token_url),true);
    if (json_charge($backjson))
    {
         $token=$backjson['access_token'];
         $openid=$backjson['openid'];
         //print_r($backjson); 
         // print($token);
         // print($openid);       
    }
    else
    {
         print('errcode1:'.$backjson['errcode'].'.errmsg:'.$backjson['errmsg'].'.');
         return;
    }
    $userinfo_url ="https://api.weixin.qq.com/sns/userinfo?access_token=$token&openid=$openid&lang=zh_CN";
    $backjson=json_decode(http_get($userinfo_url),true);
    if (!json_charge($backjson))
    {  // print ($backjson);
        print('errcode2:'.$backjson['errcode'].'.errmsg:'.$backjson['errmsg'].'.');
        return;
    
    }

    // if ($_POST['action']=='1')
    // {
    //   exit($backjson);
    //   drupal_exit();
    // }
    //echo '<meta charset="utf-8">';
    //exit(json_encode($backjson));
    //drupal_exit();
    $jumpurl='http://airnz.clients.inzen.com.cn/html/index.php?openid='.$openid;

    $result=db_query("SELECT openid FROM {wechat_userinfo} where openid=:openid",array(':openid'=>$openid))->fetchObject();
    $tempstring=(string)$result->openid;
    echo $tempstring;
    if (strlen($tempstring)>=1)
    {
      drupal_goto($jumpurl);
    }
    else
    {

      $nickname=$backjson['nickname'];
      $head=$backjson['headimgurl'];
      $timestamp=time();
      $nid = db_insert('wechat_userinfo')
      ->fields(array(
     'openid' => $openid,
     'nickname' => $nickname,
     'headurl'=>$head,
     'timestamp'=>$timestamp
     ))->execute();
     drupal_goto($jumpurl);
    }
    
    // exit(json_encode($backjson));
    drupal_exit();
    //  $code=$_GET['code'];
    //  $appId=variable_get('wechatappid', '');
    //  $appSecret=variable_get('wechatappsecret', '');
    //  $token_url="https://api.weixin.qq.com/sns/oauth2/access_token?appid=$appId&secret=$appSecret&code=$code&grant_type=authorization_code";
    //  $token_charge=variable_get('access_token', '');
    //  $currentdate=strtotime(date("y-m-d h:i:s"));
    //  if(empty($token_charge))//判断缓存中是否有获取过的ACCESS_TOKEN
    //  {//缓存中无获取过的令牌  
        
    //      $token=json_decode(http_get($token_url),true);//进行获取
    //      if (!json_charge($token))//判断是否获取成功
    //      {
    //         drupal_set_message($token['errmsg']);//获取失败，返回错误
    //      }
    //      else
    //      {
    //         $token_string=$token['access_token'];
    //         variable_set('access_token',$token_string);
    //         variable_set('token_date',date("y-m-d h:i:s"));//获取成功，对令牌进行缓存
    //      }
         
    //  }
    //  else
    //  {//缓存中有获取过的令牌
    //     if ($currentdate-(strtotime(variable_get('token_date','')))>7100)//判断令牌是否过期
    //     {//已过期
    //         $token=json_decode(http_get($token_url),true);//进行获取
    //     if (!json_charge($token))//判断是否获取成功
    //      {
    //         drupal_set_message($token['errmsg']);//获取失败,返回错误
    //      }
    //      else
    //      {
    //         $token_string=$token['access_token'];
    //         variable_set('access_token',$token_string);
    //         variable_set('token_date',date("y-m-d h:i:s"));//获取成功，对令牌进行缓存
    //      }
 
    //      }
    //      else
    //     {//未过期
    //         $token_string=variable_get('access_token', '');
    //     }

    // }

     

    //  $openid_string =$token['openid'];        
    //  $userinfo_url ="https://api.weixin.qq.com/sns/userinfo?access_token=$token_string&openid=$openid_string&lang=zh_CN";
    //  $curl=curl_init();
    //  curl_setopt($curl,CURLOPT_URL,$userinfo_url);
    //  curl_setopt($curl,CURLOPT_RETURNTRANSFER, 1);
    //  $userinfo_temp=curl_exec($curl);
    //  curl_close($curl);
    //  $userinfo=json_decode($userinfo_temp,true);
 }
 function upload_user_info()
 {   
    if (!empty($_POST['openid']))
    {

    $openid=$_POST['openid']; 
    $crtpage=$_POST['pageid'];
    $result=db_query("SELECT nickname,headurl FROM {wechat_userinfo} where openid=:openid",array(':openid'=>$openid))->fetchObject();
    $nickname=(string)$result->nickname;
    $headurl=(string)$result->headurl;
    if ($nickname==' ')
    {
      $return=array('state'=>'fail','msg'=>'wrong upload');
      echo json_encode($return);
      exit();
    }
    $result=db_query("SELECT time FROM {pagerecord} where openid=:openid and pageid=:pageid",array(':openid'=>$openid,':pageid'=>$crtpage))->fetchObject();   
    $time=(int)$result->time;
    if ($time>=1)
    {
       $nid = db_update('pagerecord')
       ->fields(array(
       'time'   => ++$time,
      ))
       ->condition('openid', $openid,'=')
       ->condition('pageid', $crtpage,'=')
       ->execute();
    }
    else
    {
       $ridflag=variable_get('ridflag', 1);
       $timestamp=time();
       $nid = db_insert('pagerecord')
       ->fields(array(
       'rid'   => $ridflag,
       'openid' => $openid,
       'nickname'=>$nickname,
       'pageid' => $crtpage,
       'time'   =>'1',
       'timestamp'=>$timestamp
       ))
       ->execute();
       $ridflag++;
       variable_set('ridflag', $ridflag);
        
     }
     $resultpage=db_query("SELECT count(pageid) as a FROM {pagerecord} where openid=:openid ",array(':openid'=>$openid))->fetchObject();
     
     //print_r($resultpage);
     $numpage=(string)$resultpage->a;
     if ($numpage=='20')
     {
       $resultreward=db_query("SELECT count(nickname) as b FROM {rewardlist} where nickname=:nickname",array(':nickname'=>$nickname))->fetchObject();
       $namenum=(string)$resultreward->b;
       //print_r($namenum);
       if ($namenum=='0') 
       { 
         $timestamp=time();
         $nid = db_insert('rewardlist')
         ->fields(array(
          'nickname'   =>$nickname,
          'headurl'    =>$headurl,
          'timestamp'  =>$timestamp
       ))
       ->execute();
       }
     }
     $return=array('state'=>'success','msg'=>'record get');
     echo json_encode($return);
    }
    else
    {
      $return=array('state'=>'fail','msg'=>'empty upload');
      echo json_encode($return);
      exit();
    }
    drupal_exit();
    
 }
 function get_ticket()
{
    $appid =variable_get('wechatappid', '');
    $appsecret=variable_get('wechatappsecret', '');
    // echo $appid;
    // echo '<br>';
    // echo $appsecret;
    // echo '<br>';
    // echo "success";
    // echo $_POST['action'];
//    if ($_POST['action']=='1')
    if (1 ==1) 
    {
        $jsticket=variable_get('jstickt','');
        $expire_time=variable_get('expiretime','');
        //echo "expire time:".$expire_time;
        if (empty($js_ticket) or empty($expire_time))
        {
           $backtemp = getWechatToken($appid,$appsecret);
           $access_token =$backtemp['access_token'];
           //print_r($backtemp);
           $backtemp = getJsapiTicket($access_token);
           $jsticket=$backtemp['ticket']; 
           variable_set('jstickt',$jsticket);
           $outline=time()+7200;
           variable_set('expiretime',$outline) ;
           //echo 'new one';
        }
        else
        {
           $current_time=time();
           //echo gettype($current_time);
           $timecount=$expire_time-$current_time;
           // echo $expire_time;
           // echo gettype($expire_time);
           // echo '<br>';
           // echo $current_time;
           // echo '<br>';
           // echo $timecount;
           if (($timecount)<300)
           {
              $backtemp = getWechatToken($appid,$appsecret);
              $access_token =$backtemp['access_token'];
              $backtemp = getJsapiTicket($access_token);
              $jsticket=$backtemp['ticket'];
              variable_set('jstickt',$jsticket);
              $outline=time()+7200;
              //echo "refresh time:".$outline;
              variable_set('expiretime', $outline);
              //echo 'refresh one';
            }
        }
            

        $noncestr = 'Newzeland4arline5';
        $jsapi_ticket = $jsticket;
        $timestamp = time();
        $url = 'http://airnz.clients.inzen.com.cn/angtest/index.php';
        $url = $_POST['url']; 
        $signature = 'jsapi_ticket=' . $jsapi_ticket . '&noncestr=' . $noncestr . '&timestamp=' . $timestamp . '&url=' . $url;
        $signature = sha1($signature); 
 
        $return = array(
          'appid'     => $appid,
          'timestamp' => $timestamp,
          'noncestr'  => $noncestr,
          'ticket'    => $jsticket,
          'signature' => $signature,
          'url'       => $url,
        );

        exit(json_encode($return));
        drupal_exit();
       
    }
}
 function get_share_count()
 {
  if (empty($_POST['openid']) || empty($_POST['url']) || empty($_POST['action']))
  {
    $return=array('status'=>'fail','msg'=>'empty post');
    //echo 'empty charge';
    exit(json_encode($return));
  }
  if (strlen($_POST['openid'])!=28)
  {
    $return=array('status'=>'fail','msg'=>'wrong openid');
    //echo 'length charge';
    exit(json_encode($return));
  }

  $openid=$_POST['openid'];
  $url=$_POST['url'];
  $action=$_POST['action'];
  $result=db_query("SELECT nickname,headurl FROM {wechat_userinfo} where openid=:openid",array(':openid'=>$openid))->fetchObject();
  $nickname=(string)$result->nickname;
  $headurl=(string)$result->headurl;
  $timestamp=time();
  $sid=(int)variable_get('sid',0);
  if($sid<1)
  {
    $sid=1;
    variable_set('sid', $sid);
  }
  
  if ($action=='1')
  {  
     
     $nid = db_insert('share_count')
         ->fields(array(
          'openid'     =>$openid,
          'nickname'   =>$nickname,
          'headurl'    =>$headurl,
          'timestamp'  =>$timestamp,
          'shareurl'   =>$url,
          'action'     =>'share to moment',
          'sid'        =>$sid
       ))
       ->execute();
       $sid++;
       variable_set('sid', $sid);
       $return=array('status'=>'success','msg'=>'share count get');
       exit(json_encode($return));
  }
  if ($action=='2')
  {

     $nid = db_insert('share_count')
         ->fields(array(
          'openid'     =>$openid,
          'nickname'   =>$nickname,
          'headurl'    =>$headurl,
          'timestamp'  =>$timestamp,
          'shareurl'   =>$url,
          'action'     =>'share to friend',
          'sid'        =>$sid
       ))
       ->execute();
       $sid++;
       variable_set('sid', $sid);
       $return=array('status'=>'success','msg'=>'share count get');
       exit(json_encode($return));
  }
 }
 function table_exist($tablename,$schemaname)
 {
    $back=db_query("SELECT * FROM {TABLES} WHERE table_schema=:table_schema and table_name=:table_name",array(':table_schema'=>$schemaname,':table_name'=>$table_name))->fetchField();
    if (isset($back))
    {
      return true;
    }
    else
    {
      return false;
    }
 }
 function http_get($url)
 {
     $curl=curl_init();
     curl_setopt($curl,CURLOPT_URL,$url);
     curl_setopt($curl,CURLOPT_RETURNTRANSFER, 1);
     $temp=curl_exec($curl);
     curl_close($curl);
     return $temp;
 }
 function json_charge($charge)
 {
  if (!empty($charge['errcode']))
  {
    return false;
  }
  else
  {
    return true;
  }
 }
 function __CreateOauthUrlForCode($redirectUrl)
  {
    $urlObj["appid"] =variable_get('wechatappid', '');
    $urlObj["redirect_uri"] = "$redirectUrl";
    $urlObj["response_type"] = "code";
    $urlObj["scope"] = "snsapi_userinfo";
    $urlObj["state"] = "STATE"."#wechat_redirect";
    $bizString = ToUrlParams($urlObj);
    return "https://open.weixin.qq.com/connect/oauth2/authorize?".$bizString;
  }
 function ToUrlParams($urlObj)
  {
    $buff = "";
    foreach ($urlObj as $k => $v)
    {
      if($k != "sign"){
        $buff .= $k . "=" . $v . "&";
      }
    }
    
    $buff = trim($buff, "&");
    return $buff;
  }
function getWechatToken($appid,$appsecret)
{
    $url="https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=$appid&secret=$appsecret";
    $backjson=json_decode(http_get($url),true);
    if (!empty($backjson))
    {
        //echo 'token suceess';
        return $backjson;
    }
    else
    {   
        $errmsg=$backjson['errcode']+$backjson['errmsg'];
        $return=array('status' => 'fail','msg' =>$backjson['errmsg']);
        return $backjson;
    }
}
function getJsapiTicket($access_token)
{
    $ticketurl = "https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=$access_token&type=jsapi";
    $backjson =json_decode(http_get($ticketurl),true);
    if ($backjson['errcode']!='0')
    {
        $errmsg=$backjson['errcode']+$backjson['errmsg'];
        $return =array('status'=>'fail','msg'=>$errmsg);
        return $return;
    }
    else
    {
        return $backjson;
    }
}


